"""
This type stub file was generated by pyright.
"""

_date_handlers = ...

def registerDateHandler(func):  # -> None:
    """Register a date handler function (takes string, returns 9-tuple date in GMT)"""
    ...
